### ISSUE TITLE
QGIS install problem

### ISSUE THREAD

**Issue by grantboxer** [techforwildlife/qgis-drone_path-plugin#1]
Good Morning, I have tried to install Drone Path in my QGIS installation and I get the following message. Are there missing dependencies I need to load?

Couldn't load plugin 'drone_path' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'drone_path.resources' 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\drone_path\__init__.py", line 35, in classFactory
    from .drone_path import DronePath
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\drone_path\drone_path.py", line 34, in 
    from .resources import *
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'drone_path.resources'

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.26.3-Buenos Aires Buenos Aires, 65e4edfdada 

Python Path:
C:\Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\sense_detection
C:/OSGeo4W/apps/qgis/./python
C:/Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis/./python/plugins
C:\OSGeo4W\bin\python39.zip
C:\OSGeo4W\apps\Python39\DLLs
C:\OSGeo4W\apps\Python39\lib
C:\OSGeo4W\bin
C:\Users\boxer\AppData\Roaming\Python\Python39\site-packages
C:\OSGeo4W\apps\Python39
C:\OSGeo4W\apps\Python39\lib\site-packages
C:\OSGeo4W\apps\Python39\lib\site-packages\win32
C:\OSGeo4W\apps\Python39\lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python39\lib\site-packages\Pythonwin
C:/Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\site-packages
C:\Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin
C:\Users\boxer\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\qgispluginsupport\qps\pyqtgraph
C:\Users\boxer\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\site-packages
C:\Users\boxer\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps
C:\Users\boxer\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\coreapps
.
D:/DropBox/Dropbox/Burgundy/GIS/DroneSurveys

**Comment by jfmoyen** [comment]
Similar error here...
Impossible de charger l'extension 'drone_path' provoque une erreur lors de l'appel à sa méthode classFactory() 

TypeError: 'QVariant' object is not subscriptable 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/moje4671/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\drone_path\__init__.py", line 36, in classFactory
    return DronePath(iface)
  File "C:\Users/moje4671/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\drone_path\drone_path.py", line 61, in __init__
    locale = QSettings().value('locale/userLocale')[0:2]
TypeError: 'QVariant' object is not subscriptable


Version de Python : 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Version de QGIS : 3.22.3-Białowieża Białowieża, 1628765ec7 

Chemin Python :
C:\Users/moje4671/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LAStools
C:\Users/moje4671/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\open_lidar_tools
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python
C:/Users/moje4671/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/moje4671/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.22.3\bin\python39.zip
C:\PROGRA~1\QGIS32~1.3\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib
C:\Program Files\QGIS 3.22.3\bin
C:\PROGRA~1\QGIS32~1.3\apps\Python39
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\GDAL-3.4.1-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\Pythonwin
C:/Users/moje4671/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\moje4671\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\QuickMultiAttributeEdit3/forms
D:/GISData/Field_Data/MassifCentral
C:\Users/moje4671/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\rvt-qgis
